### ISSUE TITLE
The submittion question

### ISSUE THREAD

**Issue by lizixiaoboluo** [JeremyLinky/YouTube-VLN#2]
Hi，thanks for your great work.

I encountered an issue when trying to submit test submission file to the leaderboard. I received the following error message: "Error: The provided trajectory moves from 6673e7995dcc444eb18cf01845cf2915 to 7606ea285d5e4a9280220c1d823fdb80 but the navigation graph contains no edge between these viewpoints. Please ensure the provided navigation trajectories are valid so that the trajectory length can be accurately calculated."

Could you please advise on how to resolve this issue?

I appreciate your response.

Thank you！！！

**Comment by JeremyLinky** [comment]
We've never been in this situation. Where did the JSON file you submitted to the leaderboard come from? Is it submitted to the R2R benchmark? Is the format correct? You'll need to carefully check the submitted JSON file generation process.

**Comment by lizixiaoboluo** [comment]
Hi，

I have already solved this issue.

Thank you for your help！

**Comment by JeremyLinky** [comment]
Happy to see that :)
