### ISSUE TITLE
Image Features Provided

### ISSUE THREAD

**Issue by HuskyKingdom** [JeremyLinky/YouTube-VLN#3]
Hi! Thanks for your awesome work.

I was trying to use your work in my research, with you providing the following instructions:
_____
1、Download the image features (total 11 files) and put them into data/YouTube-VLN/youtube_img_features:

[image features 0、](https://drive.google.com/drive/folders/142JLO8G8CFetK1-EkChswH9x4IxoHaLD?usp=sharing) [image features 1、](https://drive.google.com/drive/folders/1K2egIRzhuXWlVY6Kcn4hpa6DjinzaHQq?usp=drive_link) [image features 2、](https://drive.google.com/drive/folders/1wiECk6-8yb5vcXQ3aWdXxtK51XEP_eUE?usp=sharing) [image features 3、](https://drive.google.com/drive/folders/1waioWqRrybVFBRuABOrNZUzgbCCkwyW-?usp=sharing) [image features 4、](https://drive.google.com/drive/folders/1PnQxp2hfFVdAx7YWhlJikQPYo554sHN9?usp=sharing) [image features 5、](https://drive.google.com/drive/folders/1b5b6Y5qvi20zZ9s1D3ANMEx6nRBCr8j1?usp=sharing) [image features 6、](https://drive.google.com/drive/folders/1y61b4bE4l3FaDOVeJAcLCw2jvJ-QeRh3?usp=sharing) [image features 7、](https://drive.google.com/drive/folders/1e0j6cehnlIf60hW5ji0eenPtmjTgFRyM?usp=sharing) [image features 8、](https://drive.google.com/drive/folders/1jC360MNm66-GXS45uur271cK7HbB2VBK?usp=sharing) [image features 9、](https://drive.google.com/drive/folders/1eFQKtivQmw41NjDk3AubE2F9pHtHg0NT?usp=sharing) [image features 10](https://drive.google.com/drive/folders/1nJsK2b1HZfqeKCFFzjtDCzKZkR0LR3to?usp=sharing)
_____

You claim that there are in total 11 files, but it seems like in each link above there are files "data.mdb" and "lock.mdb", should I download all of them? (which would result in a whole more than 11 files).

**Comment by JeremyLinky** [comment]
Yes, you need to download all of them. Actually, there are 11 directories, 11*2 files :)

**Comment by HuskyKingdom** [comment]
Hi Linky, thanks for your quick reply and kind explanation.
