### ISSUE TITLE
Tips for correcting README.md

### ISSUE THREAD

**Issue by HuskyKingdom** [JeremyLinky/YouTube-VLN#4]
Hi, thank you again for your awesome work.

While trying the reproduce, I found the following errors that might help you to update the README, and make the repo even better for upcoming researchers :> :

1. In README:

-----
4.Download the [matterport-ResNet-101-faster-rcnn features](https://dl.dropbox.com/s/67k2vjgyjqel6og/matterport-ResNet-101-faster-rcnn-genome.lmdb.zip) and unzip it and then put it into data/YouTube-VLN.
-----
It appears to me that [matterport-ResNet-101-faster-rcnn features](https://dl.dropbox.com/s/67k2vjgyjqel6og/matterport-ResNet-101-faster-rcnn-genome.lmdb.zip) file should be instead in data/ directory rather than data/YouTube-VLN, as defined in test.py args.

2.  CUDA  Compatibility Issue

While running test.py, the following error pops up:

-----
NVIDIA GeForce RTX 3070 Laptop GPU with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3070 Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
-----

It indicates a problem with the compatibility between the installed PyTorch version and the CUDA capabilities of my GPU, wondering would updating the torch version causes any problems.

Thank you for your time for consulting with me for above questions :>

**Comment by JeremyLinky** [comment]
Hi, thanks for your advice! I'll check out what you mentioned sometime. I've been busy with other things lately, really sorry for that.
