### ISSUE TITLE
download.py issues

### ISSUE THREAD

**Issue by ikamran64** [JeremyLinky/YouTube-VLN#5]
python scripts/download.py
Traceback (most recent call last):
  File "scripts/download.py", line 255, in <module>
    class Arguments(tap.Tap):
AttributeError: module 'tap' has no attribute 'Tap'

hi, 
i am trying to run this file on the terminal but i keep getting the error that Tap is not an attribute.

**Comment by HuskyKingdom** [comment]
Hi,

I faced the same issue before, you can solve it by manually remove arg parsing and simply set every argument to True (as the same default of the original).

**Comment by ikamran64** [comment]
thank you for the information. problem solved

**Comment by ikamran64** [comment]
Thnak you for your helped i solved the issues. If i have any other issue
can i contact you?

Kind Regards,
Kamran Rehman

**Comment by ikamran64** [comment]
Hello Hang,
I ran into another issue and I am unable to solve it. I may need your
help,  if you know what is wrong here.
so i am trying to pre train the model but i am running into an error called
'json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)'

i am unable to find the json file as it can be a syntax error or the file
doesn't even exist. THis is the whole error message I am receiving. if u
had the same issue and you resolved it please let me know.
Kind regards,
Kamran Rehman

Experiment Folder:
 /home/kamran-rehman/anaconda3/envs/lily/YouTube-VLN/result/ytbvln_2e5_500_MRT/train6_2024-02-09_14:35:02__
Loading features reader...
Loading train dataset
Caption path: data/YouTube-VLN/ytb/merge+ytb_train.json
Testset path: {'ranking': 'data/YouTube-VLN/ytb/merge+testset.json'}
Loading test dataset
test_dataset length:202
train_dataset length:3876
Loading val datasets
val_seen_dataset length 0
val_unseen_dataset length 0
batch_size: 8
Creating dataloader
Loading model
Traceback (most recent call last):
  File "/home/kamran-rehman/anaconda3/envs/lily/lib/python3.6/runpy.py",
line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kamran-rehman/anaconda3/envs/lily/lib/python3.6/runpy.py",
line 85, in _run_code
    exec(code, run_globals)
  File "/home/kamran-rehman/anaconda3/envs/lily/YouTube-VLN/pretrain.py",
line 176, in <module>
    main()
  File "/home/kamran-rehman/anaconda3/envs/lily/YouTube-VLN/pretrain.py",
line 54, in main
    config =
BERT_CONFIG_FACTORY[args.model_name].from_json_file(args.config_file)
  File
"/home/kamran-rehman/anaconda3/envs/lily/YouTube-VLN/vilbert/vilbert.py",
line 182, in from_json_file
    params = json.load(fid)
  File
"/home/kamran-rehman/anaconda3/envs/lily/lib/python3.6/json/__init__.py",
line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook,
**kw)
  File
"/home/kamran-rehman/anaconda3/envs/lily/lib/python3.6/json/__init__.py",
line 354, in loads
    return _default_decoder.decode(s)
  File
"/home/kamran-rehman/anaconda3/envs/lily/lib/python3.6/json/decoder.py",
line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File
"/home/kamran-rehman/anaconda3/envs/lily/lib/python3.6/json/decoder.py",
line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1)
local_rank: 0 (pid: 36042) of binary:
/home/kamran-rehman/anaconda3/envs/lily/bin/python
Traceback (most recent call last):
  File "/home/kamran-rehman/anaconda3/envs/lily/lib/python3.6/runpy.py",
line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kamran-rehman/anaconda3/envs/lily/lib/python3.6/runpy.py",
line 85, in _run_code
    exec(code, run_globals)
  File
"/home/kamran-rehman/anaconda3/envs/lily/lib/python3.6/site-packages/torch/distributed/launch.py",
line 193, in <module>
    main()
  File
"/home/kamran-rehman/anaconda3/envs/lily/lib/python3.6/site-packages/torch/distributed/launch.py",
line 189, in main
    launch(args)
  File
"/home/kamran-rehman/anaconda3/envs/lily/lib/python3.6/site-packages/torch/distributed/launch.py",
line 174, in launch
    run(args)
  File
"/home/kamran-rehman/anaconda3/envs/lily/lib/python3.6/site-packages/torch/distributed/run.py",
line 713, in run
    )(*cmd_args)
  File
"/home/kamran-rehman/anaconda3/envs/lily/lib/python3.6/site-packages/torch/distributed/launcher/api.py",
line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File
"/home/kamran-rehman/anaconda3/envs/lily/lib/python3.6/site-packages/torch/distributed/launcher/api.py",
line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by HuskyKingdom** [comment]
Hi, you need to download this json file manually from the link instructed by download.py.

**Comment by ikamran64** [comment]
Thanks, it worked.

**Comment by ikamran64** [comment]
Hello Hang
I got stuck in a problem.
I hope you can help me out here.
Do you have the test.py results from youtube vln? I am unable to get it
because of the limited GPu on my system.

Secondly, how can I visualize the results like the navigation in an unseen
environment ?
