### ISSUE TITLE
About visualization examples

### ISSUE THREAD

**Issue by ivebarna** [JeremyLinky/YouTube-VLN#8]
Thanks for your great work!
Could you please give some guidance on how to get the visualization examples of the agent, like the figure 11 in your paper.

**Comment by JeremyLinky** [comment]
Hi, you can refer to [precompute_img_features.py](https://github.com/peteanderson80/Matterport3DSimulator/blob/589d091b111333f9e9f9d6cfd021b2eb68435925/scripts/precompute_img_features.py) to visualize each viewpoint, and then stitch the viewpoints together according to your trajectory.
